// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bcof.proto

package bcof

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BCOFEntry struct {
	Id        uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Signature string `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// Types that are valid to be assigned to Payload:
	//	*BCOFEntry_Sub
	//	*BCOFEntry_Data
	Payload              isBCOFEntry_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BCOFEntry) Reset()         { *m = BCOFEntry{} }
func (m *BCOFEntry) String() string { return proto.CompactTextString(m) }
func (*BCOFEntry) ProtoMessage()    {}
func (*BCOFEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_e513a4b40f9135bc, []int{0}
}

func (m *BCOFEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BCOFEntry.Unmarshal(m, b)
}
func (m *BCOFEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BCOFEntry.Marshal(b, m, deterministic)
}
func (m *BCOFEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BCOFEntry.Merge(m, src)
}
func (m *BCOFEntry) XXX_Size() int {
	return xxx_messageInfo_BCOFEntry.Size(m)
}
func (m *BCOFEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_BCOFEntry.DiscardUnknown(m)
}

var xxx_messageInfo_BCOFEntry proto.InternalMessageInfo

func (m *BCOFEntry) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BCOFEntry) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type isBCOFEntry_Payload interface {
	isBCOFEntry_Payload()
}

type BCOFEntry_Sub struct {
	Sub *BCOFEntry `protobuf:"bytes,3,opt,name=sub,proto3,oneof"`
}

type BCOFEntry_Data struct {
	Data []byte `protobuf:"bytes,4,opt,name=data,proto3,oneof"`
}

func (*BCOFEntry_Sub) isBCOFEntry_Payload() {}

func (*BCOFEntry_Data) isBCOFEntry_Payload() {}

func (m *BCOFEntry) GetPayload() isBCOFEntry_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *BCOFEntry) GetSub() *BCOFEntry {
	if x, ok := m.GetPayload().(*BCOFEntry_Sub); ok {
		return x.Sub
	}
	return nil
}

func (m *BCOFEntry) GetData() []byte {
	if x, ok := m.GetPayload().(*BCOFEntry_Data); ok {
		return x.Data
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*BCOFEntry) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*BCOFEntry_Sub)(nil),
		(*BCOFEntry_Data)(nil),
	}
}

func init() {
	proto.RegisterType((*BCOFEntry)(nil), "bcof.BCOFEntry")
}

func init() { proto.RegisterFile("bcof.proto", fileDescriptor_e513a4b40f9135bc) }

var fileDescriptor_e513a4b40f9135bc = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4a, 0xce, 0x4f,
	0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xea, 0xb9, 0x38, 0x9d, 0x9c,
	0xfd, 0xdd, 0x5c, 0xf3, 0x4a, 0x8a, 0x2a, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15,
	0x18, 0x35, 0x78, 0x83, 0x98, 0x32, 0x53, 0x84, 0x64, 0xb8, 0x38, 0x8b, 0x33, 0xd3, 0xf3, 0x12,
	0x4b, 0x4a, 0x8b, 0x52, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0x10, 0x02, 0x42, 0xca, 0x5c,
	0xcc, 0xc5, 0xa5, 0x49, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0xfc, 0x7a, 0x60, 0xa3, 0xe1,
	0x66, 0x79, 0x30, 0x04, 0x81, 0x64, 0x85, 0x44, 0xb8, 0x58, 0x52, 0x12, 0x4b, 0x12, 0x25, 0x58,
	0x14, 0x18, 0x35, 0x78, 0x3c, 0x18, 0x82, 0xc0, 0x3c, 0x27, 0x4e, 0x2e, 0xf6, 0x82, 0xc4, 0xca,
	0x9c, 0xfc, 0xc4, 0x14, 0x27, 0x8e, 0x28, 0x36, 0x3d, 0x7d, 0x90, 0xde, 0x24, 0x36, 0xb0, 0xbb,
	0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x94, 0xc2, 0x9a, 0x10, 0xa5, 0x00, 0x00, 0x00,
}
