// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.4
// source: bcof.proto

package bcof

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BCOFData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Rsize     uint32 `protobuf:"varint,2,opt,name=rsize,proto3" json:"rsize,omitempty"`
	Signature string `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Payload   []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *BCOFData) Reset() {
	*x = BCOFData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bcof_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BCOFData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BCOFData) ProtoMessage() {}

func (x *BCOFData) ProtoReflect() protoreflect.Message {
	mi := &file_bcof_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BCOFData.ProtoReflect.Descriptor instead.
func (*BCOFData) Descriptor() ([]byte, []int) {
	return file_bcof_proto_rawDescGZIP(), []int{0}
}

func (x *BCOFData) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BCOFData) GetRsize() uint32 {
	if x != nil {
		return x.Rsize
	}
	return 0
}

func (x *BCOFData) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *BCOFData) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type BCOFEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Rsize     uint32               `protobuf:"varint,2,opt,name=rsize,proto3" json:"rsize,omitempty"`
	Signature string               `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Data      []*BCOFEntrySubentry `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *BCOFEntry) Reset() {
	*x = BCOFEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bcof_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BCOFEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BCOFEntry) ProtoMessage() {}

func (x *BCOFEntry) ProtoReflect() protoreflect.Message {
	mi := &file_bcof_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BCOFEntry.ProtoReflect.Descriptor instead.
func (*BCOFEntry) Descriptor() ([]byte, []int) {
	return file_bcof_proto_rawDescGZIP(), []int{1}
}

func (x *BCOFEntry) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BCOFEntry) GetRsize() uint32 {
	if x != nil {
		return x.Rsize
	}
	return 0
}

func (x *BCOFEntry) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *BCOFEntry) GetData() []*BCOFEntrySubentry {
	if x != nil {
		return x.Data
	}
	return nil
}

type BCOFEntrySubentry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Pl:
	//	*BCOFEntrySubentry_Binary
	//	*BCOFEntrySubentry_Leaf
	Pl isBCOFEntrySubentry_Pl `protobuf_oneof:"pl"`
}

func (x *BCOFEntrySubentry) Reset() {
	*x = BCOFEntrySubentry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bcof_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BCOFEntrySubentry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BCOFEntrySubentry) ProtoMessage() {}

func (x *BCOFEntrySubentry) ProtoReflect() protoreflect.Message {
	mi := &file_bcof_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BCOFEntrySubentry.ProtoReflect.Descriptor instead.
func (*BCOFEntrySubentry) Descriptor() ([]byte, []int) {
	return file_bcof_proto_rawDescGZIP(), []int{1, 0}
}

func (m *BCOFEntrySubentry) GetPl() isBCOFEntrySubentry_Pl {
	if m != nil {
		return m.Pl
	}
	return nil
}

func (x *BCOFEntrySubentry) GetBinary() *BCOFData {
	if x, ok := x.GetPl().(*BCOFEntrySubentry_Binary); ok {
		return x.Binary
	}
	return nil
}

func (x *BCOFEntrySubentry) GetLeaf() *BCOFEntry {
	if x, ok := x.GetPl().(*BCOFEntrySubentry_Leaf); ok {
		return x.Leaf
	}
	return nil
}

type isBCOFEntrySubentry_Pl interface {
	isBCOFEntrySubentry_Pl()
}

type BCOFEntrySubentry_Binary struct {
	Binary *BCOFData `protobuf:"bytes,1,opt,name=binary,proto3,oneof"`
}

type BCOFEntrySubentry_Leaf struct {
	Leaf *BCOFEntry `protobuf:"bytes,2,opt,name=leaf,proto3,oneof"`
}

func (*BCOFEntrySubentry_Binary) isBCOFEntrySubentry_Pl() {}

func (*BCOFEntrySubentry_Leaf) isBCOFEntrySubentry_Pl() {}

var File_bcof_proto protoreflect.FileDescriptor

var file_bcof_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x62, 0x63, 0x6f, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x62, 0x63,
	0x6f, 0x66, 0x22, 0x68, 0x0a, 0x08, 0x42, 0x43, 0x4f, 0x46, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x72, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x72,
	0x73, 0x69, 0x7a, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xe0, 0x01, 0x0a,
	0x09, 0x42, 0x43, 0x4f, 0x46, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x72, 0x73, 0x69, 0x7a, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x2c,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62,
	0x63, 0x6f, 0x66, 0x2e, 0x42, 0x43, 0x4f, 0x46, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x73, 0x75,
	0x62, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x61, 0x0a, 0x08,
	0x73, 0x75, 0x62, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x28, 0x0a, 0x06, 0x62, 0x69, 0x6e, 0x61,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x63, 0x6f, 0x66, 0x2e,
	0x42, 0x43, 0x4f, 0x46, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x61,
	0x72, 0x79, 0x12, 0x25, 0x0a, 0x04, 0x6c, 0x65, 0x61, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x62, 0x63, 0x6f, 0x66, 0x2e, 0x42, 0x43, 0x4f, 0x46, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x48, 0x00, 0x52, 0x04, 0x6c, 0x65, 0x61, 0x66, 0x42, 0x04, 0x0a, 0x02, 0x70, 0x6c, 0x42,
	0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x62, 0x63, 0x6f, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_bcof_proto_rawDescOnce sync.Once
	file_bcof_proto_rawDescData = file_bcof_proto_rawDesc
)

func file_bcof_proto_rawDescGZIP() []byte {
	file_bcof_proto_rawDescOnce.Do(func() {
		file_bcof_proto_rawDescData = protoimpl.X.CompressGZIP(file_bcof_proto_rawDescData)
	})
	return file_bcof_proto_rawDescData
}

var file_bcof_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bcof_proto_goTypes = []interface{}{
	(*BCOFData)(nil),          // 0: bcof.BCOFData
	(*BCOFEntry)(nil),         // 1: bcof.BCOFEntry
	(*BCOFEntrySubentry)(nil), // 2: bcof.BCOFEntry.subentry
}
var file_bcof_proto_depIdxs = []int32{
	2, // 0: bcof.BCOFEntry.data:type_name -> bcof.BCOFEntry.subentry
	0, // 1: bcof.BCOFEntry.subentry.binary:type_name -> bcof.BCOFData
	1, // 2: bcof.BCOFEntry.subentry.leaf:type_name -> bcof.BCOFEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bcof_proto_init() }
func file_bcof_proto_init() {
	if File_bcof_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bcof_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BCOFData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bcof_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BCOFEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bcof_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BCOFEntrySubentry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_bcof_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*BCOFEntrySubentry_Binary)(nil),
		(*BCOFEntrySubentry_Leaf)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bcof_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bcof_proto_goTypes,
		DependencyIndexes: file_bcof_proto_depIdxs,
		MessageInfos:      file_bcof_proto_msgTypes,
	}.Build()
	File_bcof_proto = out.File
	file_bcof_proto_rawDesc = nil
	file_bcof_proto_goTypes = nil
	file_bcof_proto_depIdxs = nil
}
