// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.4
// source: brkbd.proto

package brkbd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeySeq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq []*KeySeq_KeyCode `protobuf:"bytes,1,rep,name=seq,proto3" json:"seq,omitempty"`
}

func (x *KeySeq) Reset() {
	*x = KeySeq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brkbd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeySeq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeySeq) ProtoMessage() {}

func (x *KeySeq) ProtoReflect() protoreflect.Message {
	mi := &file_brkbd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeySeq.ProtoReflect.Descriptor instead.
func (*KeySeq) Descriptor() ([]byte, []int) {
	return file_brkbd_proto_rawDescGZIP(), []int{0}
}

func (x *KeySeq) GetSeq() []*KeySeq_KeyCode {
	if x != nil {
		return x.Seq
	}
	return nil
}

type KeySeq_KeyCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code []byte `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *KeySeq_KeyCode) Reset() {
	*x = KeySeq_KeyCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brkbd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeySeq_KeyCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeySeq_KeyCode) ProtoMessage() {}

func (x *KeySeq_KeyCode) ProtoReflect() protoreflect.Message {
	mi := &file_brkbd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeySeq_KeyCode.ProtoReflect.Descriptor instead.
func (*KeySeq_KeyCode) Descriptor() ([]byte, []int) {
	return file_brkbd_proto_rawDescGZIP(), []int{0, 0}
}

func (x *KeySeq_KeyCode) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

var File_brkbd_proto protoreflect.FileDescriptor

var file_brkbd_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x62, 0x72, 0x6b, 0x62, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x62,
	0x72, 0x6b, 0x62, 0x64, 0x22, 0x50, 0x0a, 0x06, 0x4b, 0x65, 0x79, 0x53, 0x65, 0x71, 0x12, 0x27,
	0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62, 0x72,
	0x6b, 0x62, 0x64, 0x2e, 0x4b, 0x65, 0x79, 0x53, 0x65, 0x71, 0x2e, 0x4b, 0x65, 0x79, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x03, 0x73, 0x65, 0x71, 0x1a, 0x1d, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x62, 0x72, 0x6b, 0x62,
	0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_brkbd_proto_rawDescOnce sync.Once
	file_brkbd_proto_rawDescData = file_brkbd_proto_rawDesc
)

func file_brkbd_proto_rawDescGZIP() []byte {
	file_brkbd_proto_rawDescOnce.Do(func() {
		file_brkbd_proto_rawDescData = protoimpl.X.CompressGZIP(file_brkbd_proto_rawDescData)
	})
	return file_brkbd_proto_rawDescData
}

var file_brkbd_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_brkbd_proto_goTypes = []interface{}{
	(*KeySeq)(nil),         // 0: brkbd.KeySeq
	(*KeySeq_KeyCode)(nil), // 1: brkbd.KeySeq.KeyCode
}
var file_brkbd_proto_depIdxs = []int32{
	1, // 0: brkbd.KeySeq.seq:type_name -> brkbd.KeySeq.KeyCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_brkbd_proto_init() }
func file_brkbd_proto_init() {
	if File_brkbd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_brkbd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeySeq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brkbd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeySeq_KeyCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_brkbd_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_brkbd_proto_goTypes,
		DependencyIndexes: file_brkbd_proto_depIdxs,
		MessageInfos:      file_brkbd_proto_msgTypes,
	}.Build()
	File_brkbd_proto = out.File
	file_brkbd_proto_rawDesc = nil
	file_brkbd_proto_goTypes = nil
	file_brkbd_proto_depIdxs = nil
}
